CREATE DATABASE FW
AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY DEFAULT COLLATE USING SYSTEM PAGESIZE 32768;
CONNECT TO FW;
UPDATE DATABASE CONFIG FOR FW USING LOGFILSIZ 65536;
UPDATE DATABASE CONFIG FOR FW USING LOGPRIMARY 40;
UPDATE DATABASE CONFIG FOR FW USING NUM_LOG_SPAN 32;
UPDATE DATABASE CONFIG FOR FW USING AUTO_MAINT ON;
UPDATE DATABASE CONFIG FOR FW USING AUTO_TBL_MAINT ON;
UPDATE DATABASE CONFIG FOR FW USING AUTO_RUNSTATS ON;
UPDATE DATABASE CONFIG FOR FW USING AUTO_REORG ON;
UPDATE DATABASE CONFIG FOR FW USING AUTO_DB_BACKUP ON;
CREATE USER TEMPORARY TABLESPACE FWTEMP PAGESIZE 32K BUFFERPOOL IBMDEFAULTBP;
CREATE BUFFERPOOL FW_04KBP IMMEDIATE SIZE 1000 PAGESIZE 4K;
CREATE REGULAR TABLESPACE TS_REG04_FW PAGESIZE 4K BUFFERPOOL FW_04KBP;
CREATE BUFFERPOOL FW_08KBP IMMEDIATE SIZE 1000 PAGESIZE 8K;
CREATE REGULAR TABLESPACE TS_REG08_FW PAGESIZE 8K BUFFERPOOL FW_08KBP;
CREATE BUFFERPOOL FW_16KBP IMMEDIATE SIZE 1000 PAGESIZE 16K;
CREATE REGULAR TABLESPACE TS_REG16_FW PAGESIZE 16K BUFFERPOOL FW_16KBP;
CONNECT RESET;